### ISSUE TITLE
Shot won’t stop in micra 

### ISSUE THREAD

**Issue by chcha** [tatemazer/AcaiaArduinoBLE#16]
Hi Tate - I finally successfully installed the board into my Micra this weekend and it appears to be connected well. My acaia lunar is taring and starting its timer when I start a shot but I am not getting the 3 sec beep and when I turn the lever to the off position at 3 sec, the shot stops.

I connected with light blue as in the iOS instructions and was able to set/confirm 36 grams setting.  I’m not that familiar with troubleshooting Arduino but am willing to give it a try? I’m a Mac user.

**Comment by tatemazer** [comment]
Hi @chcha , moving this discussion to the discord. We can troubleshoot there. If there ends up being a bug in the firmware, we can open a case on the git repo. Thanks!
