### ISSUE TITLE
How to get mac address of scale?

### ISSUE THREAD

**Issue by SirusPTB** [tatemazer/AcaiaArduinoBLE#8]
How to get mac address of scale?

**Comment by FelixMau** [comment]
You can simply connect your scale via Bluetooth to your (Android) smartphone or Computer then you should be able to see the Mac Adress. As far as I know the Acaia is usually in Pairing mode.

**Comment by SirusPTB** [comment]
Thanks for the feed back but where exactly can I see it? What Android app I have tried several and can't see the mac address.

**Comment by FelixMau** [comment]
If you go to your Bluetooth settings a device connected should look something likee this:

![Screenshot_20240503-161211~2](https://github.com/tatemazer/AcaiaArduinoBLE/assets/98911066/6006237f-5e0b-4fa9-81d7-92e5a3a89c58)

**Comment by tatemazer** [comment]
Hi SirusPTB, I hope you were able to find your MAC address. If not, I also like to use the example code in the ArduinoBLE library Found in the Arduino IDE under File/Examples/ArduinoBLE/Central/PeripheralExplorer. This will list the MAC addresses as the device scans for them.
